# -*- coding: utf-8 -*-
"""Day1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eOytZ2AlAUQAtNf5d0XceqVLDULrqSjh
"""

List=[int(i) for i in input('Enter the values:').split()]
List.sort()
print(List)